# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd2e0a51b2a7356a4767a266ba39972511d4fcbe2f026135dd8664617268a5adad825188ae2d283d4ae0c4c1c8f658cc51b2c4ac73f5510f0b95873f8dd7651d

test:
  secret_key_base: fdd5d08bbf0f351efdd5cae447a4764a6fb7305ee6bdd976ad542eb81a954d48c45e75882951737d99d194c80ef57262e908ea09453976691848bff117e87872

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
